# Site specific settings
title: "Edgar Montano's Developer Blog"
name: "Edgar Montano's Developer Blog"
keywords: "edgar montano, edgar, montano, developer, blog, tech blog, programming blog, git, gud, git gud, git blog, good blog"
baseurl: ""
url: "http://em2532.github.io"
description: "Get the lastest tips and tricks on programming and development techniques. Your personal guide to getting gud."
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter:
facebook:
github: em2532
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
